# https://www.appveyor.com/docs/appveyor-yml/
environment:

  # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
  # /E:ON and /V:ON options are not enabled in the batch script intepreter
  # See: http://stackoverflow.com/a/13751649/163740
  CMD_IN_ENV: "cmd /E:ON /V:ON /C obvci_appveyor_python_build_env.cmd"

  matrix:

    # Pre-installed Python versions, which Appveyor may upgrade to
    # a later point release.
    # See: http://www.appveyor.com/docs/installed-software#python

    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.x"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7.x"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python36"
      PYTHON_VERSION: "3.6.x"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6.x"
      PYTHON_ARCH: "64"


install:
  # If there is a newer build queued for the same PR, cancel this one.
  # The AppVeyor 'rollout builds' option is supposed to serve the same
  # purpose but it is problematic because it tends to cancel builds pushed
  # directly to master instead of just PR builds (or the converse).
  # credits: JuliaLang developers.
  - SET PATH=%PYTHON%;%PYTHON%\\Scripts;%path%
  - python --version
  - pip --version
  - pip install -r requirements.txt
  - pip install pytest coverage
  - pip list
  - dir

build_script:
  # Build the compiled extension
  #- cl gco_source\LinkedBlockList.cpp /link /out:LinkedBlockList.obj
  #- cl gco_source\graph.cpp /link /out:graph.obj
  #- cl gco_source\maxflow.cpp /link /out:maxflow.obj
  #- cl gco_source\GCoptimization.cpp /link /out:GCoptimization.obj
  #- cl cgco.cpp /link /out:cgco.obj
  #- cl LinkedBlockList.obj graph.obj maxflow.obj GCoptimization.obj cgco.obj /link /dll /out:libcgco.dll
  #- cl /EHsc test_wrapper.cpp libcgco.lib
  - python setup.py build_ext --inplace
  - dir

test_script:
  - coverage run --source=gco -m py.test gco test_examples.py -v --doctest-modules --junitxml=pytest_junit.xml

after_test:
  # If tests are successful, create binary packages for the project.
  - python setup.py install

on_success:
  - coverage report