name: PyPI Release

# https://help.github.com/en/actions/reference/events-that-trigger-workflows
on:  # Trigger the workflow on push or pull request, but only for the main branch
  push:
    branches: [master]
  pull_request:
    branches: [master]
    paths:
      - ".github/workflows/release-pypi.yml"
  release:
    types: [published]

# based on https://github.com/pypa/gh-action-pypi-publish

jobs:
  build-sdist:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@v2
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: python -m pip install --user --upgrade setuptools wheel
    - name: Build source
      run: |
        pip install -q setuptools numpy
        python setup.py sdist
        ls -lh dist/

    - uses: actions/upload-artifact@v4
      with:
        name: sdist-${{ github.sha }}
        path: dist

  build-wheels:
    runs-on: ${{ matrix.os }}
    needs: build-sdist
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
    - uses: actions/checkout@master

    - name: Building wheels
      uses: pypa/cibuildwheel@v3.1.3
      env:
        # Disable building PyPy wheels on all platforms
        CIBW_SKIP: pp*

    - uses: actions/upload-artifact@v4
      with:
        name: cibw-wheels-${{ strategy.job-index }}
        path: ./wheelhouse/*.whl

  collect-pkgs:
    runs-on: ubuntu-latest
    needs: build-wheels
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: sdist-${{ github.sha }}
        path: dist
    - name: Download 📥
      uses: actions/download-artifact@v4
      with:
        # download all build artifacts
        pattern: cibw-wheels-*
        merge-multiple: true
        path: dist

    - run: ls -lh dist/
    - uses: actions/upload-artifact@v4
      with:
        name: pypi-packages-${{ github.sha }}
        path: dist

  publish-pypi:
    runs-on: ubuntu-latest
    needs: collect-pkgs
    if: startsWith(github.event.ref, 'refs/tags') || github.event_name == 'release'
    steps:
    - uses: actions/checkout@master
    - uses: actions/download-artifact@v4
      with:
        name: pypi-packages-${{ github.sha }}
        path: dist
    - run: ls -l dist/

    # We do this, since failures on test.pypi aren't that bad
    - name: Publish to Test PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.test_pypi_password }}
        repository_url: https://test.pypi.org/legacy/

    - name: Publish distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.pypi_password }}

  upload-package:
    runs-on: ubuntu-latest
    needs: collect-pkgs
    if: startsWith(github.event.ref, 'refs/tags') || github.event_name == 'release'
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v4
      with:
        name: pypi-packages-${{ github.sha }}
        path: dist
    - run: ls -lh dist/

    - name: Upload to release
      uses: AButler/upload-release-assets@v2.0
      with:
        files: 'dist/*'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
